### ISSUE TITLE
Could not find method layout()

### ISSUE THREAD

**Issue by 24glinka** [elevennl/gradle-node-plugin#6]
Using Gradle 7.2, with this configuration:

id "com.moowork.node" version "1.3.1"
id "com.moowork.gulp" version "1.3.0"

node {
    version='10.14.0'
    npmVersion = '6.4.1'
    distBaseUrl = 'https://nodejs.org/dist'
    download = true
    npmWorkDir = file('npm')
    nodeModulesDir = file(npmDir)
    workDir = file(npmDir)
}

I received this error:  
**Could not find method layout() for arguments [pattern, com.moowork.gradle.node.task.SetupTask$_addRepository_closure5$_closure7@63011f99] on object of type org.gradle.api.internal.artifacts.repositories.DefaultIvyArtifactRepository** .

Java version: openjdk 15.

What could be the root cause?
Tell me what I should add as further information.

**Comment by Shuyinsama** [comment]
Dear @24glinka 

This package has not been updated for use with Gradle 7.0+ and we have no plans to update this package any further.
We made this fork to use the original plugin with Gradle 6 + Gulp support, since then we are starting to migrate to https://github.com/node-gradle/gradle-node-plugin.

My recommendation is to start using https://github.com/node-gradle/gradle-node-plugin
They have support for Gradle 7+ and are also in active development. It should almost be a drop-in replacement.
They did remove the `GulpTask` in favor of the `NpxTask` but as far as I know if you only use node/yarn tasks you can use their plugin with very minimal changes!

This fork will be removed in the near future.

I did not foresee this package being used by other people but I will have a look at updating the README to clearly state not to use this package due to no further development in this fork.

Our apologies!
